cyor10/PF-HyperEvent

api/package.json
api/src/controllers/createEvent.js
api/src/controllers/user.js
api/src/db.js
api/src/models/Cart.js
api/src/routes/events.js
api/src/routes/users.js
api/src/utils/cloudinaryConfig.js
client/src/app/events/page.js
client/src/app/login/page.js
client/src/app/payment/error/page.js
client/src/app/payment/page.js
client/src/app/payment/pending/page.js
client/src/app/payment/success/page.js
client/src/app/signup/page.js

todo andando con cloudinary implementado en back para registro de usuarios y creación de events

feat(*): cloudinary implemented

---

api/src/app.js
api/src/controllers/mercado_pago.js
api/src/models/User.js
api/src/utils/mandarEmail.js
client/src/app/payment/page.js

paymentsuccess

---

client/src/app/components/NavBar/NavBar.js
client/src/app/create_event/page.js
client/src/app/detail/[id]/page.js
client/src/app/events/page.js
client/src/app/login/page.js
client/src/app/payment/page.js
client/src/app/signup/page.js
client/src/utils/axiosInstance.js

feat(client): created base url for comunications

---

api/src/controllers/createEvent.js
api/src/controllers/getCategories.js
api/src/controllers/getEvents.js
api/src/models/Category.js
api/src/models/Event.js
api/src/models/Ticket.js
api/src/models/User.js
api/src/utils/loadDb.js
client/src/app/components/NavBar/NavBar.js
client/src/app/create_event/page.js
client/src/app/detail/[id]/page.js
client/src/app/events/page.js
client/src/app/login/page.js
client/src/app/payment/page.js
client/src/app/signup/page.js
client/src/utils/axiosInstance.js

fix(api): freeze table name, remove unnecesary variables

---

api/index.js
api/src/controllers/mercado_pago.js
api/src/db.js
api/src/utils/loadDb.js
client/src/app/components/NavBar/NavBar.js
client/src/app/detail/[name]/page.js
client/src/app/events/page.js
client/src/app/page.js
client/src/app/payment/page.js
client/src/app/signup/page.js
client/src/utils/axiosInstance.js

Fix(api)/functional db

---

client/src/app/components/NavBar/NavBar.js
client/src/app/components/SearchBar/SearchBar.js
client/src/redux/features/counter/counterSlice.js
client/src/redux/features/events/counterSlice.js
client/src/redux/store.js

feat(*):searchBar

---

client/package-lock.json
client/package.json
client/src/app/api/auth/[...nextauth]/route.js
client/src/app/components/NavBar/NavBar.js
client/src/app/login/page.js
client/src/redux/features/counter/counterSlice.js
client/src/redux/provider.js
client/src/utils/axiosInstance.js

feat(client)/nextauth(google)

---

client/src/app/create_event/page.js
client/src/app/login/page.js
client/src/app/signup/page.js
client/src/utils/axiosInstance.js
client/src/validate/validate.js

login.js
signup.js
validations.js
create_event.js

disableSubmitsButtons

---

api/src/utils/loadDb.js

mejorado el tiempo. de la carga de la db

loadDb.js refactor

---

api/src/controllers/index.js
api/src/controllers/location/getCitiesByState.js
api/src/controllers/location/getCountries.js
api/src/controllers/location/getStatesByCounty.js
api/src/controllers/location/setCities.js
api/src/controllers/location/setCountries.js
api/src/controllers/location/setStates.js
api/src/models/Countries.js
api/src/models/States.js
api/src/utils/states.json

refactor(api): modularize location controllers and include iso code

---

client/src/app/components/SearchBar/Pagination.js
client/src/app/components/SearchBar/SearchBar.js
client/src/redux/features/events/counterSlice.js
client/src/utils/axiosInstance.js
client/tailwind.config.js

Faltan cambion todavia en searchBar el pull request es para ir subiendo en partes

fix(client):searchBar, Pagination, tailwind, redux/events

---

api/src/controllers/getSales.js
api/src/controllers/index.js
api/src/routes/index.js
api/src/routes/sales.js
client/next.config.js
client/src/app/payment/error/page.js
client/src/app/payment/success/page.js

feat(app)/sales

---

api/src/controllers/index.js
api/src/controllers/user.js
api/src/routes/users.js
client/src/app/components/NavBar/NavBar.js
client/src/app/layout.js
client/src/app/login/page.js
client/src/app/page.js
client/src/app/payment/[price]/page.js
client/src/redux/provider.js

Se le asigna Token a los usuarios de google que se crean y loguean, se deja de mostrar los dos usuarios,aunque debe haber una mejor forma de arreglarlo( es el dispatch(getUser) del navBar)

fix(client)/googleToken

---

api/src/controllers/category/getCategories.js
api/src/controllers/index.js
client/src/app/events/page.js
client/src/app/page.js

feat(*) show categories with events

---

api/src/controllers/event/getTopEvents.js
api/src/controllers/index.js
api/src/routes/events.js
client/src/app/page.js

feat(*): create service for get top events

---

api/src/controllers/getSales.js
api/src/controllers/mercado_pago.js
api/src/email/mandarEmail.js
client/src/app/payment/[price]/page.js
client/src/app/payment/error/page.js
client/src/app/payment/pending/page.js
client/src/app/payment/success/page.js

Se manda un mail si el status es failure,pending o success. se agrego informacion que se manda al post sales

feat(mail)/sales

---

api/src/controllers/getSales.js
api/src/controllers/mercado_pago.js
api/src/email/mandarEmail.js
client/src/app/events/page.js
client/src/app/payment/[price]/page.js
client/src/app/payment/error/page.js
client/src/app/payment/pending/page.js
client/src/app/payment/success/page.js

Arreglado el error de cargar categorias numerosas (reading "null")
Arreglado el error de payment(espacios en blanco)

Fix(client)/payment bugs

---

api/src/models/Sales.js

timestamps for sales

---

client/src/app/components/NavBar/NavBar.js
client/src/app/components/SearchBar/EmptyState.js
client/src/app/components/SearchBar/RecentSearch.js
client/src/app/components/SearchBar/SearchBar.js
client/src/app/search/page.js
client/src/redux/features/events/counterSlice.js

feat(client): new implement search filters

---

api/src/models/Event.js
api/src/models/User.js

borrado logico

---

client/src/app/form/PartTwo.js
client/src/redux/features/location/locationSlice.js
client/src/redux/store.js

feat(client) implement location services for the form

---

api/src/controllers/category/setCategories.js
api/src/controllers/event/createMasiveEvents.js

feat(api): update rules set categories

---

client/src/app/components/SearchBar/Pagination.js
client/src/app/components/SearchBar/RecentSearch.js
client/src/app/components/SearchBar/SearchBar.js
client/src/redux/features/events/counterSlice.js

feat(client): include logical in recent search

---

api/src/controllers/event/searchEvents.js
client/src/app/components/Card/Card.js
client/src/app/components/Cards/Cards.js
client/src/app/components/Categories/Categories.js
client/src/app/components/SearchBar/RecentSearch.js
client/src/app/components/SearchBar/SearchBar.js
client/src/app/events/[name]/page.js
client/src/app/page.js

fix(client): solve bugs in navigation

---

client/src/app/about/page.js
client/src/app/detail/[name]/page.js

fix(client): add attributes in detail and about

---

client/src/app/about/page.js
client/src/app/form/PartTwo.js

alfin le consegui foto a douglas quien no conosca a douglas que no opine xD

detalles pequeños

---

api/src/models/Event.js
client/src/app/form/PartFour.js
client/src/app/form/PartOne.js

fix(*): update design

---

client/src/app/components/Carousel/Carousel.js
client/src/app/page.js

correcciones

---

api/src/controllers/event/getEvents.js
api/src/utils/countries.json
client/src/app/detail/[name]/page.js
client/src/app/payment/[name]/page.js

fix(*): solved view active events
